# Devstack configuration file.
# local.conf file for OpenStack Compute Node.
# You will have to update the following options below to match your setup.
# SERVICE_HOST -> Should point to the OpenStack controller node.


[[local|localrc]]
RECLONE=yes
#OFFLINE=True
DATA_DIR=$DEST/data
SCREEN_LOGDIR=$DATA_DIR/logs
LOGFILE=$SCREEN_LOGDIR/stack.sh.log
LOGDAYS=1

ADMIN_PASSWORD=password
MYSQL_PASSWORD=password
RABBIT_PASSWORD=password
SERVICE_PASSWORD=password
SERVICE_TOKEN=token

MULTI_HOST=1

#Set the SERVICE_HOST IP address below
SERVICE_HOST=10.43.104.12
MYSQL_HOST=$SERVICE_HOST
RABBIT_HOST=$SERVICE_HOST
GLANCE_HOSTPORT=$SERVICE_HOST:9292

ENABLED_SERVICES=n-cpu,q-agt

Q_PLUGIN=ml2
Q_ML2_TENANT_NETWORK_TYPE=gre
ENABLE_TENANT_TUNNELS=True

[[post-config|/etc/neutron/plugins/ml2/ml2_conf.ini]]
[ml2]
mechanism_drivers = openvswitch,linuxbridge,l2population
[securitygroup]
enable_security_group = False
firewall_driver = neutron.agent.firewall.NoopFirewallDriver
[agent]
tunnel_types = gre
l2_population = True

#[[post-config|/etc/neutron/l3_agent.ini]]
#[DEFAULT]
#external_network_bridge =

[[post-config|/etc/nova/nova.conf]]
[DEFAULT]
security_group_api = nova
firewall_driver = nova.virt.firewall.NoopFirewallDriver
